#!/usr/bin/env bash
# automate setting up a redirect for nginx
apt update
apt install nginx -y
/etc/init.d/nginx restart
cp /var/www/html/index.html /var/www/html/index.html.bak
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
echo 'Hello World!' > /var/www/html/index.html
sed -i '/server_name _;/a \ location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-available/default
/etc/init.d/nginx restart
