#!/usr/bin/env bash
# automate setting up a redirect for nginx
sed -i '/server_name _;/a \ location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-available/default
/etc/init.d/nginx restart
