#!/usr/bin/env bash
# automate setting up a redirect for nginx
apt update
apt install nginx -y
/etc/init.d/nginx restart
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
echo "Ceci n'est pas une page" > '/var/www/html/404.html'
sed -i '/server_name _;/a \ error_page 404 /404.html; location = /404.html {root /var/www/html;}' /etc/nginx/sites-available/default
/etc/init.d/nginx restart
