#!/usr/bin/env bash
# setup haproxy for new server
apt update && sudo apt upgrade
apt-get install -y haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
echo -e "backend web-backend\n\tbalance roundrobin\n\tserver web-01 54.158.79.193:80 check\n\tserver web-02 52.204.95.113:80 check" >> /etc/haproxy/haproxy.cfg
echo -e "frontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend" >> /etc/haprxoy/haproxy.cfg
systemctl restart haproxy
