#!/usr/bin/env bash
# prints Best school
#+ and prints bad, good at 4 and 8

i=1

while (( i <= 10 ))
do
	if [ "$i" -eq 4 ]
	then
		echo "bad luck"
	elif [ "$i" -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i = i + 1 ))
done
